### ISSUE TITLE
Float32 necessary?

### ISSUE THREAD

**Issue by 0xymoro** [Gryphe/BlockMerge_Gradient#1]
Hi, running some experiments with 70b merging, and it's been a struggle trying to fit things into vram. Wonder why you load it in float32 instead of saving memory and doing bfloat16? Is there a tangible difference (for me there's not been)?

**Comment by Gryphe** [comment]
Hi there! It's definitely not necessary to work solely in float32 and in the case of 70b merges I highly recommend adding the .half() function after each of the models have loaded.

model1 = model1.to(device)
model1.half()
model1.eval()

Include the same line for model2 but make sure to remove it further down the script! Otherwise it'll complain and not save the results.
